#!/bin/bash

s=0
b=$((128*256))
e=$b

for k in {1..4}; do
  for j in {1..8}; do
    > cl256K_APP${k}_${j}
    for i in $(eval echo {$s..$e}); do
      printf -v ID "c%08d" $i
      printf ${ID}"|1|"${ID}"|svtpvtpass|1:0:/APP/$j/CAR/"${ID}"||\n" >> cl256K_APP${k}_${j}
    done
    echo cl256K_APP${k}_${j} $s..$e
    s=$(($e+1))
    e=$(($e+$b))
  done
done

cat cl256K_APP1_1 cl256K_APP1_2 cl256K_APP1_3 cl256K_APP1_4 cl256K_APP1_5 cl256K_APP1_6 cl256K_APP1_7 cl256K_APP1_8 > cl256K_APP12

cat cl256K_APP2_1 cl256K_APP2_2 cl256K_APP2_3 cl256K_APP2_4 cl256K_APP2_5 cl256K_APP2_6 cl256K_APP2_7 cl256K_APP2_8 > cl256K_APP34

cat cl256K_APP3_1 cl256K_APP3_2 cl256K_APP3_3 cl256K_APP3_4 cl256K_APP3_5 cl256K_APP3_6 cl256K_APP3_7 cl256K_APP3_8 > cl256K_APP56

cat cl256K_APP4_1 cl256K_APP4_2 cl256K_APP4_3 cl256K_APP4_4 cl256K_APP4_5 cl256K_APP4_6 cl256K_APP4_7 cl256K_APP4_8 > cl256K_APP78

for k in {1..4}; do
  for j in {1..8}; do
    echo rm cl256K_APP${k}_${j} 
    rm -f cl256K_APP${k}_${j} 
  done
done

