#!/bin/bash +x

source manualrun_HA_JMS

###############################################################################
## FN_RUN()  ##################################################################
fn__run() {
  id=$1

  while [ "${stop}" == "false" ]; do
    fn__checkfree
    fn__checkidle

    if [ "${stop}" == "false" ]; then
      printf "[%s] /niagara/scale/manualrunHATopic ${INSTANCES} %d 86400\n" ${hn} ${id}
      /niagara/scale/manualrunHATopic ${INSTANCES} ${id} 86400
      ((id+=${INSTANCES}))
      CLIENT_COUNT=$((${INSTANCES}+${id}))
      if [ "${CLIENT_COUNT}" -gt "${MAX_CLIENT_COUNT}" ];then
         stop="true"
      fi
      sleep 20s
    fi
  done
}

#############################################################################
###  Start of MAIN
###

fn__run ${1-0}

