#!/bin/bash 

source ./test.cfg

DEBUG=0

if [ -z $1 ]; then
  NODE=msserver01a
  ID=c00000001
  TOPIC=/APP/a01/CAR/${ID}
else
  NODE=${APPLIANCE[$1]}
  ID=${CAR[$1]}
  TOPIC=/APP/${APP[$1]}/CAR/${ID}
fi

ENDPOINT=`/niagara/test/scripts/getclusterserverendpointport.py -c ${CLUSTER} -e SVT-CarsInternetEndpoint -a ${NODE}`

if [ ${DEBUG} -ne 0 ]; then
  echo CLUSTER=${CLUSTER}
  echo NODE=${NODE}
  echo ENDPOINT=${ENDPOINT}
  echo QOS=${QOS}
  echo MESSAGES=${MESSAGES}
  echo ID=${ID}
fi


echo java -Djavax.net.ssl.trustStore=${CACERTS} -Djavax.net.ssl.trustStorePassword=${PASSWORD} svt.mqtt.mq.MqttSample -mqtt 3.1.1 -i ${ID} -u ${ID} -p ${PW} -a publish -t ${TOPIC} -s ssl://${ENDPOINT} -n ${MESSAGES} -O -v -e true -sslProtocol ${PROTOCOL} -w ${RATE} -q ${QOS}
java -Djavax.net.ssl.trustStore=${CACERTS} -Djavax.net.ssl.trustStorePassword=${PASSWORD} svt.mqtt.mq.MqttSample -mqtt 3.1.1 -i ${ID} -u ${ID} -p ${PW} -a publish -t ${TOPIC} -s ssl://${ENDPOINT} -n ${MESSAGES} -O -v -e true -sslProtocol ${PROTOCOL} -w ${RATE} -q ${QOS}



