#!/bin/bash

i=198.23.126.155
p=5004
CL=/niagara/test/svt_atelm/SL/P02/localns/Q0/cl256K_APP12

#clients-14
#export IMAServer="$i"
#export IMAPort="$p"
export IMAServer="198.23.126.154:$i 169.53.4.4:$i 169.53.4.5:$i 169.53.4.6:$i 169.53.4.7:$i 169.53.4.8:$i 169.53.4.9:$i"
export IMAPort="$p $p $p $p $p $p $p"
export DelayCount=1
export DelayTime=1200
export SourcePortLo=5000
export UseSecureConn=1
#export PipeCommands=1
export SSLClientMeth=TLSv12
export SSLCipher=AES128-GCM-SHA256
export PATH=/root/workspace/application/server_ship/bin:/root/workspace/application/client_ship/bin:${PATH}
export LD_LIBRARY_PATH=/root/workspace/application/server_ship/lib:/root/workspace/application/client_ship/lib:/usr/lib:${LD_LIBRARY_PATH}
export IOProcThreads=6
export RetryDelayTime=2.0
export RetryDelayBackoff=1.01

if [ -z $1 ]; then
export RATE=262144
else 
export RATE=$1
fi

echo mqttbench -d 0 -tx 0:0:/APP/1/:1:$((${RATE}/2)):2 -r ${RATE} -s 32-32 -cl $CL -recon 10
mqttbench -d 0 -tx 0:0:/APP/1/:1:$((${RATE}/2)):2 -r ${RATE} -s 32-32 -cl $CL -recon 10
#gdb mqttbench 

