#!/bin/bash

i=169.45.136.83
p=5004
CL=/niagara/test/svt_atelm/SL/P02/localns/Q0/cl256K_APP56

#clients-14
#export IMAServer="$i"
#export IMAPort="$p"
export IMAServer="198.23.126.158:$i 169.45.139.234:$i 169.45.139.235:$i 169.45.139.236:$i 169.45.139.237:$i 169.45.139.238:$i 169.45.139.239:$i"
export IMAPort="$p $p $p $p $p $p $p"
export DelayCount=1
export DelayTime=1200
export SourcePortLo=5000
export UseSecureConn=1
#export PipeCommands=1
export SSLClientMeth=TLSv12
export SSLCipher=AES128-GCM-SHA256
export PATH=/root/workspace/application/server_ship/bin:/root/workspace/application/client_ship/bin:${PATH}
export LD_LIBRARY_PATH=/root/workspace/application/server_ship/lib:/root/workspace/application/client_ship/lib:/usr/lib:${LD_LIBRARY_PATH}
export IOProcThreads=6
export RetryDelayTime=2.0
export RetryDelayBackoff=1.01

if [ -z $1 ]; then
export RATE=262144
else 
export RATE=$1
fi

echo mqttbench -d 0 -tx 0:0:/APP/1/:1:$((${RATE}/2)):2 -r ${RATE} -s 32-32 -cl $CL -recon 10
mqttbench -d 0 -tx 0:0:/APP/1/:1:$((${RATE}/2)):2 -r ${RATE} -s 32-32 -cl $CL -recon 10
#gdb mqttbench 

