#!/bin/bash

i=198.23.126.156
p=5004
CL=/niagara/test/svt_atelm/SL/P02/localns/Q0/cl256K_APP34

#clients-14
#export IMAServer="$i"
#export IMAPort="$p"
export IMAServer="198.23.126.144:$i 169.45.139.228:$i 169.45.139.229:$i 169.45.139.230:$i 169.45.139.231:$i 169.45.139.232:$i 169.45.139.233:$i"
e
export IMAPort="$p $p $p $p $p $p $p"
export DelayCount=1
export DelayTime=1200
export SourcePortLo=5000
export UseSecureConn=1
#export PipeCommands=1
export SSLClientMeth=TLSv12
export SSLCipher=AES128-GCM-SHA256
export PATH=/root/workspace/application/server_ship/bin:/root/workspace/application/client_ship/bin:${PATH}
export LD_LIBRARY_PATH=/root/workspace/application/server_ship/lib:/root/workspace/application/client_ship/lib:/usr/lib:${LD_LIBRARY_PATH}
export IOProcThreads=6
export RetryDelayTime=2.0
export RetryDelayBackoff=1.01

if [ -z $1 ]; then
export RATE=262144
else 
export RATE=$1
fi

echo mqttbench -d 0 -tx 0:0:/APP/1/:1:$((${RATE}/2)):2 -r ${RATE} -s 32-32 -cl $CL -recon 10
mqttbench -d 0 -tx 0:0:/APP/1/:1:$((${RATE}/2)):2 -r ${RATE} -s 32-32 -cl $CL -recon 10
#gdb mqttbench 

