#!/bin/bash
set -x

if [ -z $1 ]; then
  w=1000
else
  w=$1
fi

  set -x
# DEBUG=-Djava.util.logging.config.file=./paho/pahopub.properties

  java ${DEBUG} svt.mqtt.mq.MqttSample -a publish -t "/USER/Li/APP/MsgOrdering" -m "b" -s "tcp://10.10.10.10:17915 tcp://10.10.10.10:17915" -N -1 -q 2 -w $w -O -i p`hostname` -c false > /niagara/test/scale/Li/start_pub.log 2>&1

  set +x




