#!/bin/bash 

source ./test.cfg

DEBUG=0

if [ -z $1 ]; then
  NODE=msserver01a
  ID=APP1
  TOPIC=\$SharedSubscription/dog//APP/a01/#
else
  NODE=${APPLIANCE[$1]}
  ID=${APP[$1]}
  TOPIC=${SHARED}/APP/${ID}/#
fi

ID=C00000011
RESENDID=C00000021
PW=svtpvtpass
ENDPOINT=`/niagara/test/scripts/getclusterserverendpointport.py -c ${CLUSTER} -e SVT-IntranetEndpoint -a ${NODE}`
gatherpubserver=tcp://${ENDPOINT}
subserver=tcp://${ENDPOINT}

if [ ${DEBUG} -ne 0 ]; then
  echo CLUSTER=${CLUSTER}
  echo NODE=${NODE}
  echo ENDPOINT=${ENDPOINT}
  echo QOS=${QOS}
  echo MESSAGES=${MESSAGES}
fi



echo test_template5_MQTTClient -vv -debug -a subscribe -mqtt 3.1.1 -q 2 -t '\$SharedSubscription/dog//svtGroup0/chat' -s ${subserver} -i u0000011 -u u0000011 -p imasvtest -v -c false  -Nm 1 -resendURI ${gatherpubserver} -resendID u0000021 -resendTopic /svtGroup0/chat/gather

echo java svt.mqtt.mq.MqttSample -vv -debug -a subscribe -mqtt 3.1.1 -q ${QOS} -t '$SharedSubscription/dog//svtGroup0/chat' -s ${subserver} -i ${ID} -u ${ID} -p svtpvtpass -v -c false  -Nm ${MINUTES} -resendURI ${gatherpubserver} -resendID ${RESENDID} -resendTopic /svtGroup0/chat/gather
java svt.mqtt.mq.MqttSample -vv -debug -a subscribe -mqtt 3.1.1 -q ${QOS} -t '$SharedSubscription/dog//svtGroup0/chat' -s ${subserver} -i ${ID} -u ${ID} -p svtpvtpass -v -c false  -Nm ${MINUTES} -resendURI ${gatherpubserver} -resendID ${RESENDID} -resendTopic /svtGroup0/chat/gather -maxInflight 32000
