/*
 * Copyright (c) 2021 Contributors to the Eclipse Foundation
 * 
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 * 
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * imaSnmpCVMib.h
 *
 *  Created on: 2014-7-15
 *      Author:
 */

#ifndef IMASNMPCVMIB_H_
#define IMASNMPCVMIB_H_

#define IMA_SNMP_STATISTICSSERVER_OID 4
#define IMA_SNMP_STATISTICSSERVER_MIB IMA_SNMP_STAT_MIB, IMA_SNMP_STATISTICSSERVER_OID

#define IMA_SNMP_CV_ACTIVECONNECTIONS_OID 1
#define IMA_SNMP_CV_ACTIVECONNECTIONS_MIB IMA_SNMP_STATISTICSSERVER_MIB, IMA_SNMP_CV_ACTIVECONNECTIONS_OID

#define IMA_SNMP_CV_TOTALCONNECTIONS_OID 2
#define IMA_SNMP_CV_TOTALCONNECTIONS_MIB IMA_SNMP_STATISTICSSERVER_MIB, IMA_SNMP_CV_TOTALCONNECTIONS_OID

#define IMA_SNMP_CV_MSGREAD_OID 3
#define IMA_SNMP_CV_MSGREAD_MIB IMA_SNMP_STATISTICSSERVER_MIB, IMA_SNMP_CV_MSGREAD_OID

#define IMA_SNMP_CV_MSGWRITE_OID 4
#define IMA_SNMP_CV_MSGWRITE_MIB IMA_SNMP_STATISTICSSERVER_MIB, IMA_SNMP_CV_MSGWRITE_OID

#define IMA_SNMP_CV_BYTESREAD_OID 5
#define IMA_SNMP_CV_BYTESREAD_MIB IMA_SNMP_STATISTICSSERVER_MIB, IMA_SNMP_CV_BYTESREAD_OID

#define IMA_SNMP_CV_BYTESWRITE_OID 6
#define IMA_SNMP_CV_BYTESWRITE_MIB IMA_SNMP_STATISTICSSERVER_MIB, IMA_SNMP_CV_BYTESWRITE_OID

#define IMA_SNMP_CV_BADCONNCOUNT_OID 7
#define IMA_SNMP_CV_BADCONNCOUNT_MIB IMA_SNMP_STATISTICSSERVER_MIB, IMA_SNMP_CV_BADCONNCOUNT_OID

#define IMA_SNMP_CV_TOTALENDPOINTS_OID 8
#define IMA_SNMP_CV_TOTALENDPOINTS_MIB IMA_SNMP_STATISTICSSERVER_MIB, IMA_SNMP_CV_TOTALENDPOINTS_OID

#define IMA_SNMP_CV_BUFFEREDMESSAGES_OID 9
#define IMA_SNMP_CV_BUFFEREDMESSAGES_MIB IMA_SNMP_STATISTICSSERVER_MIB, IMA_SNMP_CV_BUFFEREDMESSAGES_OID

#define IMA_SNMP_CV_RETAINEDMESSAGES_OID 10
#define IMA_SNMP_CV_RETAINEDMESSAGES_MIB IMA_SNMP_STATISTICSSERVER_MIB, IMA_SNMP_CV_RETAINEDMESSAGES_OID

#define IMA_SNMP_CV_EXPIREDMESSAGES_OID 11
#define IMA_SNMP_CV_EXPIREDMESSAGES_MIB IMA_SNMP_STATISTICSSERVER_MIB, IMA_SNMP_CV_EXPIREDMESSAGES_OID

/* function declarations */
#ifdef __cplusplus
    extern "C" {
#endif

       int ima_snmp_init_cv_mibs();

#ifdef __cplusplus
    }
#endif


#endif /* IMASNMPCVMIB_H_ */
