#!/bin/bash 

source ./test.cfg

DEBUG=0

if [ -z $1 ]; then
  NODE=msserver01a
  ID[1]=c00110000
  ID[2]=c00120000
  ID[3]=c00130000
  ID[4]=c00140000
  APPID=a01
else
  NODE=${APPLIANCE[$1]}
  printf -v ID[1] "c%08d" $((${CAR[$1]}+10000))
  printf -v ID[2] "c%08d" $((${CAR[$1]}+20000))
  printf -v ID[3] "c%08d" $((${CAR[$1]}+30000))
  printf -v ID[4] "c%08d" $((${CAR[$1]}+40000))
fi


ENDPOINT=`/niagara/test/scripts/getclusterserverendpointport.py -c ${CLUSTER} -e SVT-CarsInternetEndpoint -a ${NODE}`
SERVER=${ENDPOINT/:*/}
PORT=${ENDPOINT/*:/}


if [ ${DEBUG} -ne 0 ]; then
  echo CLUSTER=${CLUSTER}
  echo NODE=${NODE}
  echo ENDPOINT=${ENDPOINT}
  echo QOS=${QOS}
  echo MESSAGES=${MESSAGES}
  echo ID=${ID}
fi



for i in {1..4}; do 
  echo java -Xss128K -Xzero -Xms128M -Xmx128M -Xshareclasses -Djavax.net.debug=false -Djavax.net.ssl.trustStore=${CACERTS} -Djavax.net.ssl.trustStorePassword=${PASSWORD} svt.scale.vehicle.SVTVehicle -server "${SERVER}" -userName ${ID[$i]} -password "svtpvtpass" -port ${PORT} -qos ${QOS} -paho $((${CARS}/4)) -messages ${MESSAGES} -vverbose ${VERBOSE} -listener false -iotf ${IOTF} -ssl ${SSL} -cleanSession false -rate 60 -verbose_connect ${VERBOsE_CONNECT} -genClientID false -verbose_connectionLost true -reconnectDelay 60000  -keepAlive 900 -connectionTimeout 600 -connectionThrottle 5 -order ${ORDER} -appid ${APP[$i]}
  java -Xss128K -Xzero -Xms128M -Xmx128M -Xshareclasses -Djavax.net.debug=false -Djavax.net.ssl.trustStore=${CACERTS} -Djavax.net.ssl.trustStorePassword=${PASSWORD} svt.scale.vehicle.SVTVehicle -server "${SERVER}" -userName ${ID[$i]} -password "svtpvtpass" -port ${PORT} -qos ${QOS} -paho $((${CARS}/4)) -messages ${MESSAGES} -vverbose ${VERBOSE} -listener false -iotf ${IOTF} -ssl ${SSL} -cleanSession false -rate 60 -verbose_connect ${VERBOsE_CONNECT} -genClientID false -verbose_connectionLost true -reconnectDelay 60000  -keepAlive 900 -connectionTimeout 600 -connectionThrottle 5 -order ${ORDER} -appid ${APP[$i]} &
done

