#!/bin/bash

#ismserver=`getserver`
ismserver=10.10.10.10
port=16102
#port=16555
#port=16999
qos=0
appid=1

echo ismserver is ${ismserver}

echo java svt.mqtt.mq.MqttSample -a subscribe -t "/APP/${appid}/#"  -s tcp://${ismserver}:${port} -N -1 -v -q ${qos} -c true 
java svt.mqtt.mq.MqttSample -a subscribe -t "/APP/${appid}/#"  -s tcp://${ismserver}:${port} -N -1 -q ${qos} -c true -v |tee ./start_subr1.log 2>&1



