#!/bin/bash

if [ -z $1 ]; then
  count=100
  echo Attempting to send ${count} messages....
else
  count=$1
fi

ismserver=`getserver`
#ismserver=10.10.10.10
#port=16104
#port=16502
port=16111
qos=0
appid=1

echo ismserver is ${ismserver}

set -x
java -Djavax.net.ssl.keyStore=/niagara/test/svt_jmqtt/ssl/cacerts.jks -Djavax.net.ssl.keyStorePassword=k1ngf1sh -Djavax.net.ssl.trustStore=/niagara/test/svt_jmqtt/ssl/cacerts.jks -Djavax.net.ssl.trustStorePassword=k1ngf1sh svt.mqtt.mq.MqttSample -a publish -t /APP/1/`hostname`  -s ssl://${ismserver}:${port} -n ${count} -v


