#!/bin/bash

ismserver=10.10.10.10
port=16102
qos=0

#echo ismserver is ${ismserver}

echo java svt.mqtt.mq.MqttSample -a subscribe -t "/APP/#" -i `hostname` -s tcp://${ismserver}:${port} -N -1 -q ${qos} -c true 
java svt.mqtt.mq.MqttSample -a subscribe -t "/APP/#" -i `hostname`A -s tcp://${ismserver}:${port} -N -1 -q ${qos} -c true &
java svt.mqtt.mq.MqttSample -a subscribe -t "/APP/#" -i `hostname`B -s tcp://${ismserver}:${port} -N -1 -q ${qos} -c true 
#> /dev/null
