#!/bin/bash +x
source /niagara/test/scripts/ISMsetup.sh

# This method always returns Primary First, yet BOTH have to be accessible
#TESTROOT=$(eval echo $\{${THIS}_TESTROOT\})
#declare -a list
#
#s1=`${TESTROOT}/scripts/getPrimaryServerHostAddr.sh`
#s2=`${TESTROOT}/scripts/getStandbyServerHostAddr.sh`
#
#if [ "${s1}" == "error" ]; then
#   list=${s2}
#elif [ "${s2}" == "error" ]; then
#   list=${s1}
#else
#   list=( $s1 $s2 )
#fi
#
#for (( i=0 ; i<${#list[@]} ; i++ ));
#do
#   echo ${list[${i}]}
#done

# This method always works if the source was successful
for i in $(eval echo {1..${A_COUNT}}); do
  echo $(eval echo \$\{A${i}_HOST\})
done
