#!/bin/bash


if [ -z "$1" ]; then
  for i in `ls -1`; do 
     echo putall $i
     putall $i
  done
else
  d=`pwd`
  for ip in `getClientList`; do
    echo scp $1 ${ip}:$d
    scp $1 ${ip}:$d
  done
fi
