#!/bin/bash


#clients-14
export IMAServer="169.54.242.25"
export IMAPort="5004"
#export IMAServer="169.53.4.4:169.54.242.25 169.53.4.5:169.54.242.25 169.53.4.6:169.54.242.25 169.53.4.7:169.54.242.25 169.53.4.8:169.54.242.25 169.53.4.9:169.54.242.25"
#export IMAPort="5004 5004 5004 5004 5004 5004"
export DelayCount=1
export DelayTime=1000
export SourcePortLo=5000
export UseSecureConn=1
#export PipeCommands=1
export SSLClientMeth=TLSv12
export SSLCipher=AES128-GCM-SHA256
export PATH=/root/workspace/application/server_ship/bin:/root/workspace/application/client_ship/bin:${PATH}
export LD_LIBRARY_PATH=/root/workspace/application/server_ship/lib:/root/workspace/application/client_ship/lib:/usr/lib:${LD_LIBRARY_PATH}
export IOProcThreads=8

if [ -z $1 ]; then
export RATE=15000
else 
export RATE=$1
fi

echo mqttbench -d 600 -tx 0:0:/APP/1/:1:$((${RATE}/2)):2 -r ${RATE} -s 32-32 -cl /niagara/test/svt_atelm/SL/B01/cl01A -recon 10
mqttbench -d 600 -tx 0:0:/APP/1/:1:$((${RATE}/2)):2 -r ${RATE} -s 32-32 -cl /niagara/test/svt_atelm/SL/B01/cl01A -recon 10
#gdb mqttbench 

