#!/bin/bash
#   printf ${ID}"|/APP/$j/CAR/"${ID}"|"${ID}"|svtpvtpass\n"

  for i in {0..439999}; do
    printf -v ID "c%08d" $i
    printf ${ID}"|/APP/$((i%10))/CAR/"${ID}"\n"
  done

  for i in {440000..496999}; do
    printf -v ID "c%08d" $i
    printf ${ID}"|/APP/$((i%6+3))a/CAR/"${ID}"\n"
  done
